apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-manager
  labels:
    app: plugins
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: deployment-manager
  template:
    metadata:
      labels:
        app: deployment-manager
    spec:
      containers:
        - name: deployment-manager
          image: 652084867515.dkr.ecr.eu-west-1.amazonaws.com/deployment-manager:dev
          imagePullPolicy: Always
          env:
            {{- toYaml .Values.spec.env | nindent 12 }}
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 125m
              memory: 50Mi
