apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions
  labels:
    app: plugins
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: 652084867515.dkr.ecr.eu-west-1.amazonaws.com/transactions:dev
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: 'leemons-secrets'
                  key: MONGO_URI
            - TRANSPORTER: $(TEAM_PLUGINS_NATS_PORT)

          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 125m
              memory: 50Mi
