labels:
  env: dev
  team: plugins
spec:
  ingress:
    host:
    type: alb

commonEnv:
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: 'leemons-secrets'
        key: MONGO_URI
  - name: RELOAD_I18N_ON_EVERY_INSTALL
    value: "true"
  - name: RELOAD_WIDGETS_ON_EVERY_INSTALL
    value: "true"
  - name: RELOAD_MENUS_ON_EVERY_INSTALL
    value: "true"
  - name: RELOAD_MENU_ITEMS_ON_EVERY_INSTALL
    value: "true"
  - name: DISABLE_AUTO_INIT
    value: "false"
  - name: DEBUG
    value: "false"