labels:
  env: dev
  team: plugins
spec:
  ingress:
    host:
    type: alb

commonEnv:
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: 'leemons-secrets'
        key: MONGO_URI
  - name: RELOAD_I18N_ON_EVERY_INSTALL
    value: "true"
  - name: RELOAD_WIDGETS_ON_EVERY_INSTALL
    value: "true"
  - name: RELOAD_MENUS_ON_EVERY_INSTALL
    value: "true"
  - name: RELOAD_MENU_ITEMS_ON_EVERY_INSTALL
    value: "true"
  - name: DISABLE_AUTO_INIT
    value: "false"
  - name: DEBUG
    value: "false"
  - name: TRANSPORTER
    value: "nats://$(TEAM_PLUGINS_NATS_PORT_4222_TCP_ADDR):$(TEAM_PLUGINS_NATS_PORT_4222_TCP_PORT)"

images:
  - name: "academic-calendar"
    tag: "dev"
  - name: "academic-portfolio"
    tag: "dev"
  - name: "admin"
    tag: "dev"
  - name: "assignables"
    tag: "dev"
  - name: "attendance-control"
    tag: "dev"
  - name: "board-messages"
    tag: "dev"
  - name: "bulk-template"
    tag: "dev"
  - name: "calendar"
    tag: "dev"
  - name: "comunica"
    tag: "dev"
  - name: "content-creator"
    tag: "dev"
  - name: "curriculum"
    tag: "dev"
  - name: "dashboard"
    tag: "dev"
  - name: "dataset"
    tag: "dev"
  - name: "deployment-manager"
    tag: "dev"
  - name: "emails"
    tag: "dev"
  - name: "emails-aws-ses"
    tag: "dev"
  - name: "emails-smtp"
    tag: "dev"
  - name: "families"
    tag: "dev"
  - name: "families-emergency-numbers"
    tag: "dev"
  - name: "feedback"
    tag: "dev"
  - name: "fundae"
    tag: "dev"
  - name: "grades"
    tag: "dev"
  - name: "layout"
    tag: "dev"
  - name: "learning-paths"
    tag: "dev"
  - name: "leebrary"
    tag: "dev"
  - name: "menu-builder"
    tag: "dev"
  - name: "mqtt-aws-iot"
    tag: "dev"
  - name: "mqtt-socket-io"
    tag: "dev"
  - name: "multilanguage"
    tag: "dev"
  - name: "onboarding"
    tag: "dev"
  - name: "package-manager"
    tag: "dev"
  - name: "scorm"
    tag: "dev"
  - name: "scores"
    tag: "dev"
  - name: "tasks"
    tag: "dev"
  - name: "tests"
    tag: "dev"
  - name: "timetable"
    tag: "dev"
  - name: "transactions"
    tag: "dev"
  - name: "users"
    tag: "dev"
  - name: "widgets"
    tag: "dev"
  - name: "xapi"
    tag: "dev"
