labels:
  env: dev
  team: plugins
spec:
  env:
    - name: MONGO_URI
      valueFrom:
        configMapKeyRef:
          name: 'leemons-secrets'
          key: MONGO_URI
    - name: RELOAD_I18N_ON_EVERY_INSTALL
      value: "true"
    - name: RELOAD_WIDGETS_ON_EVERY_INSTALL
      value: "true"
    - name: RELOAD_MENUS_ON_EVERY_INSTALL
      value: "true"
    - name: RELOAD_MENU_ITEMS_ON_EVERY_INSTALL
      value: "true"
    - name: DISABLE_AUTO_INIT
      value: "true"
    - name: DEBUG
      value: "false"
  ingress:
    host:
    type: alb
