apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: plugins
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:dev
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 125m
              memory: 50Mi
