apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: plugins
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 652084867515.dkr.ecr.eu-west-1.amazonaws.com/gateway:dev
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: 'leemons-secrets'
                  key: MONGO_URI
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 125m
              memory: 50Mi
