apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: team-plugins
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 3000
      protocol: TCP
      name: https

  type: NodePort
  selector:
    app: gateway
