apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: team-plugins
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: gateway
