jaeger:
  agent:
    nodeSelector:
      intent: addons
  collector:
    nodeSelector:
      intent: addons
  query:
    nodeSelector:
      intent: addons
  ingester:
    nodeSelector:
      intent: addons
