apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test
  namespace: "test"
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: app-test
  destination:
    namespace: test
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: addons/test
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true