apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: team-plugins
  source:
    repoURL: {{ .Values.repoUrl }}
    path: addons/cert-manager
    targetRevision: main
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m