{{- range .Values.images }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: plugins
    {{- toYaml $.Values.labels | nindent 4 }}
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      nodeSelector:
        intent: apps
      containers:
      - name: {{ .name }}
        image: "{{ .name }}:{{ .tag }}"
        image: "652084867515.dkr.ecr.eu-west-1.amazonaws.com/{{ .name }}:{{ .tag }}"
        imagePullPolicy: Always
        env: {{- toYaml $.Values.commonEnv | nindent 12 }}
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
---
{{- end }}