{{- range .Values.images }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: plugins
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ .name }}:{{ .tag }}"
        imagePullPolicy: Always
        env: {{- toYaml .Values.commonEnv | nindent 12 }}
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 125m
            memory: 50Mi
{{- end }}