apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: plugins
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: 652084867515.dkr.ecr.eu-west-1.amazonaws.com/users:dev
          imagePullPolicy: Always
          env:
            {{- toYaml .Values.commonEnv | nindent 12 }}
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 125m
              memory: 50Mi
